#!/usr/bin/env bash

allhistory()
{
    for i in `ls --color=never -t "$HOME"/.history`;
    do
        echo
        echo $'\e[33;1m'$i$'\e[0m'
        cat $i
    done | less -FR
}

summarisehistory()
{
    cut -f1-2 "-d " ~/.history/* | sort | uniq -c |sort -n -r | less
}

loadhistory()
{
    if [ $# -eq 0 ]
    then
        echo -e "${BRed}Choose a history file${Color_Off}";
        ls "$HOME/.history"
        return 1
    fi

    local newHist="$1"
    if [[ "${newHist##$HOME/.history/}" == "$newHist" ]]; then
        newHist="$HOME/.history/$newHist"
    fi

    local currHist="$HISTFILE"
    HISTFILE="$newHist"
    history -c
    history -r
    HISTFILE="$currHist"
}

continuehistory()
{
    newHist="$1"
    HISTFILE="$newHist"
    history -c
    history -r
}

grephistory()
{
    grep --color="always" -r "$1" "$HOME/.history" | less -FXR
}

# http://askubuntu.com/a/80882
# Multiple history files
[[ -d ~/.history ]] || mkdir ~/.history
HISTFILE=~/.history/history_$(date +%Y-%m-%d-%H-%M-%S)
# close any old history file by zeroing HISTFILESIZE
HISTFILESIZE=0
# then set HISTFILESIZE to a large value
HISTFILESIZE=4096
HISTSIZE=4096

# load history from most recent session
latestHistory=$(ls --color=never ~/.history | sort -n | tail -1)
if [[ ! -z $latestHistory ]]; then
    loadhistory $latestHistory
fi